"""
Django settings for report_engine project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&s0pc=bk!^ij)tqk)^g5bt=or#&9@wj)@3lmza!_nxzc9#h*pd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'report_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'report_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'reports_app': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Financial Aid System Integration Configuration
# Implements requirement: The report engine shall support future integration with 
# financial aid systems to automate or assist in payment processing.
FINANCIAL_AID_SYSTEMS = {
    # Example Banner configuration (disabled by default)
    # To enable, set 'enabled': True and provide actual credentials
    'banner': {
        'type': 'banner',
        'enabled': False,  # Set to True when ready to integrate
        'base_url': 'https://banner.university.edu',  # Replace with actual URL
        'api_key': '',  # Add API key from environment variable in production
        'timeout': 30,
        'retry_attempts': 3,
        'retry_delay_seconds': 5,
    },
    
    # Example Workday configuration (disabled by default)
    'workday': {
        'type': 'workday',
        'enabled': False,  # Set to True when ready to integrate
        'base_url': 'https://workday.university.edu',  # Replace with actual URL
        'username': '',  # Add from environment variable in production
        'password': '',  # Add from environment variable in production
        'tenant': '',  # Workday tenant ID
        'timeout': 30,
    },
    
    # Add other financial aid systems as needed
    # Example: PeopleSoft, Jenzabar, etc.
}

# Financial Aid Integration Settings
FINANCIAL_AID_INTEGRATION = {
    'default_system': 'banner',  # Default system to use
    'auto_submit_enabled': False,  # Whether to automatically submit approved disbursements
    'require_manual_approval': True,  # Require manual approval before submission
    'batch_processing_enabled': True,  # Enable batch disbursement processing
    'batch_size': 50,  # Maximum disbursements per batch
    'export_directory': BASE_DIR / 'financial_aid_exports',  # Directory for export files
    'archive_exports': True,  # Keep copies of exported files
    'notification_emails': [],  # Email addresses to notify of disbursement status
}
