# Generated by Django 5.2.7 on 2025-11-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=64, unique=True)),
                ('netid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('minor', models.CharField(blank=True, max_length=255, null=True)),
                ('gpa', models.FloatField(default=0.0)),
                ('academic_level', models.CharField(blank=True, max_length=64)),
                ('expected_graduation', models.DateField(blank=True, null=True)),
                ('academic_achievements', models.JSONField(blank=True, default=list)),
                ('financial_info', models.JSONField(blank=True, default=dict)),
                ('essays', models.JSONField(blank=True, default=list)),
                ('academic_history', models.JSONField(blank=True, default=list)),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('committee_feedback', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-created_at'],
            },
        ),
    ]
