# Generated by Django 5.2.7 on 2025-11-05 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=255)),
                ('award_date', models.DateTimeField()),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursement_dates', models.JSONField(default=list)),
                ('requirements_met', models.JSONField(default=list)),
                ('requirements_pending', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('revoked', 'Revoked')], max_length=20)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('essays_evaluation', models.JSONField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('committee_feedback', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='reports_app.applicant')),
            ],
            options={
                'verbose_name': 'Scholarship Award',
                'verbose_name_plural': 'Scholarship Awards',
                'ordering': ['-award_date'],
            },
        ),
    ]
