# Generated by Django 5.2.7 on 2025-11-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0003_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerInformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scholarship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.CharField(max_length=100)),
                ('request_details', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfillment_notes', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='reports_app.applicant')),
            ],
            options={
                'verbose_name': 'Reviewer Information Request',
                'verbose_name_plural': 'Reviewer Information Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
