# Generated by Django 5.2.7 on 2025-11-09 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0004_reviewerinformationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=255)),
                ('decision', models.CharField(choices=[('awarded', 'Awarded'), ('not_awarded', 'Not Awarded'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Additional reviewer/committee comments', null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_decisions', to='reports_app.applicant')),
            ],
            options={
                'verbose_name': 'Award Decision',
                'verbose_name_plural': 'Award Decisions',
                'ordering': ['-decided_at'],
                'unique_together': {('applicant', 'scholarship_name')},
            },
        ),
    ]
